// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package snowing.messages.pb;

public final class Msgs {
  private Msgs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code snowing.messages.pb.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOGIN = 0;</code>
     */
    LOGIN(0),
    /**
     * <code>LOGIN_RESULT = 1;</code>
     */
    LOGIN_RESULT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>LOGIN = 0;</code>
     */
    public static final int LOGIN_VALUE = 0;
    /**
     * <code>LOGIN_RESULT = 1;</code>
     */
    public static final int LOGIN_RESULT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return LOGIN;
        case 1: return LOGIN_RESULT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return snowing.messages.pb.Msgs.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:snowing.messages.pb.Type)
  }

  public interface MsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:snowing.messages.pb.Msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.snowing.messages.pb.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.snowing.messages.pb.Type type = 1;</code>
     * @return The type.
     */
    snowing.messages.pb.Msgs.Type getType();

    /**
     * <code>.snowing.messages.pb.Login login = 2;</code>
     * @return Whether the login field is set.
     */
    boolean hasLogin();
    /**
     * <code>.snowing.messages.pb.Login login = 2;</code>
     * @return The login.
     */
    snowing.messages.pb.Msgs.Login getLogin();
    /**
     * <code>.snowing.messages.pb.Login login = 2;</code>
     */
    snowing.messages.pb.Msgs.LoginOrBuilder getLoginOrBuilder();

    /**
     * <code>.snowing.messages.pb.LoginResult loginResult = 3;</code>
     * @return Whether the loginResult field is set.
     */
    boolean hasLoginResult();
    /**
     * <code>.snowing.messages.pb.LoginResult loginResult = 3;</code>
     * @return The loginResult.
     */
    snowing.messages.pb.Msgs.LoginResult getLoginResult();
    /**
     * <code>.snowing.messages.pb.LoginResult loginResult = 3;</code>
     */
    snowing.messages.pb.Msgs.LoginResultOrBuilder getLoginResultOrBuilder();

    public snowing.messages.pb.Msgs.Msg.UnionCase getUnionCase();
  }
  /**
   * Protobuf type {@code snowing.messages.pb.Msg}
   */
  public  static final class Msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:snowing.messages.pb.Msg)
      MsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Msg() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Msg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              snowing.messages.pb.Msgs.Login.Builder subBuilder = null;
              if (unionCase_ == 2) {
                subBuilder = ((snowing.messages.pb.Msgs.Login) union_).toBuilder();
              }
              union_ =
                  input.readMessage(snowing.messages.pb.Msgs.Login.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((snowing.messages.pb.Msgs.Login) union_);
                union_ = subBuilder.buildPartial();
              }
              unionCase_ = 2;
              break;
            }
            case 26: {
              snowing.messages.pb.Msgs.LoginResult.Builder subBuilder = null;
              if (unionCase_ == 3) {
                subBuilder = ((snowing.messages.pb.Msgs.LoginResult) union_).toBuilder();
              }
              union_ =
                  input.readMessage(snowing.messages.pb.Msgs.LoginResult.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((snowing.messages.pb.Msgs.LoginResult) union_);
                union_ = subBuilder.buildPartial();
              }
              unionCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return snowing.messages.pb.Msgs.internal_static_snowing_messages_pb_Msg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return snowing.messages.pb.Msgs.internal_static_snowing_messages_pb_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              snowing.messages.pb.Msgs.Msg.class, snowing.messages.pb.Msgs.Msg.Builder.class);
    }

    private int unionCase_ = 0;
    private java.lang.Object union_;
    public enum UnionCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      LOGIN(2),
      LOGINRESULT(3),
      UNION_NOT_SET(0);
      private final int value;
      private UnionCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static UnionCase valueOf(int value) {
        return forNumber(value);
      }

      public static UnionCase forNumber(int value) {
        switch (value) {
          case 2: return LOGIN;
          case 3: return LOGINRESULT;
          case 0: return UNION_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public UnionCase
    getUnionCase() {
      return UnionCase.forNumber(
          unionCase_);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.snowing.messages.pb.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.snowing.messages.pb.Type type = 1;</code>
     * @return The type.
     */
    public snowing.messages.pb.Msgs.Type getType() {
      @SuppressWarnings("deprecation")
      snowing.messages.pb.Msgs.Type result = snowing.messages.pb.Msgs.Type.valueOf(type_);
      return result == null ? snowing.messages.pb.Msgs.Type.UNRECOGNIZED : result;
    }

    public static final int LOGIN_FIELD_NUMBER = 2;
    /**
     * <code>.snowing.messages.pb.Login login = 2;</code>
     * @return Whether the login field is set.
     */
    public boolean hasLogin() {
      return unionCase_ == 2;
    }
    /**
     * <code>.snowing.messages.pb.Login login = 2;</code>
     * @return The login.
     */
    public snowing.messages.pb.Msgs.Login getLogin() {
      if (unionCase_ == 2) {
         return (snowing.messages.pb.Msgs.Login) union_;
      }
      return snowing.messages.pb.Msgs.Login.getDefaultInstance();
    }
    /**
     * <code>.snowing.messages.pb.Login login = 2;</code>
     */
    public snowing.messages.pb.Msgs.LoginOrBuilder getLoginOrBuilder() {
      if (unionCase_ == 2) {
         return (snowing.messages.pb.Msgs.Login) union_;
      }
      return snowing.messages.pb.Msgs.Login.getDefaultInstance();
    }

    public static final int LOGINRESULT_FIELD_NUMBER = 3;
    /**
     * <code>.snowing.messages.pb.LoginResult loginResult = 3;</code>
     * @return Whether the loginResult field is set.
     */
    public boolean hasLoginResult() {
      return unionCase_ == 3;
    }
    /**
     * <code>.snowing.messages.pb.LoginResult loginResult = 3;</code>
     * @return The loginResult.
     */
    public snowing.messages.pb.Msgs.LoginResult getLoginResult() {
      if (unionCase_ == 3) {
         return (snowing.messages.pb.Msgs.LoginResult) union_;
      }
      return snowing.messages.pb.Msgs.LoginResult.getDefaultInstance();
    }
    /**
     * <code>.snowing.messages.pb.LoginResult loginResult = 3;</code>
     */
    public snowing.messages.pb.Msgs.LoginResultOrBuilder getLoginResultOrBuilder() {
      if (unionCase_ == 3) {
         return (snowing.messages.pb.Msgs.LoginResult) union_;
      }
      return snowing.messages.pb.Msgs.LoginResult.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != snowing.messages.pb.Msgs.Type.LOGIN.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (unionCase_ == 2) {
        output.writeMessage(2, (snowing.messages.pb.Msgs.Login) union_);
      }
      if (unionCase_ == 3) {
        output.writeMessage(3, (snowing.messages.pb.Msgs.LoginResult) union_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != snowing.messages.pb.Msgs.Type.LOGIN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (unionCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (snowing.messages.pb.Msgs.Login) union_);
      }
      if (unionCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (snowing.messages.pb.Msgs.LoginResult) union_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof snowing.messages.pb.Msgs.Msg)) {
        return super.equals(obj);
      }
      snowing.messages.pb.Msgs.Msg other = (snowing.messages.pb.Msgs.Msg) obj;

      if (type_ != other.type_) return false;
      if (!getUnionCase().equals(other.getUnionCase())) return false;
      switch (unionCase_) {
        case 2:
          if (!getLogin()
              .equals(other.getLogin())) return false;
          break;
        case 3:
          if (!getLoginResult()
              .equals(other.getLoginResult())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      switch (unionCase_) {
        case 2:
          hash = (37 * hash) + LOGIN_FIELD_NUMBER;
          hash = (53 * hash) + getLogin().hashCode();
          break;
        case 3:
          hash = (37 * hash) + LOGINRESULT_FIELD_NUMBER;
          hash = (53 * hash) + getLoginResult().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static snowing.messages.pb.Msgs.Msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static snowing.messages.pb.Msgs.Msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static snowing.messages.pb.Msgs.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static snowing.messages.pb.Msgs.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static snowing.messages.pb.Msgs.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static snowing.messages.pb.Msgs.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static snowing.messages.pb.Msgs.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static snowing.messages.pb.Msgs.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static snowing.messages.pb.Msgs.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static snowing.messages.pb.Msgs.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static snowing.messages.pb.Msgs.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static snowing.messages.pb.Msgs.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(snowing.messages.pb.Msgs.Msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code snowing.messages.pb.Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:snowing.messages.pb.Msg)
        snowing.messages.pb.Msgs.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return snowing.messages.pb.Msgs.internal_static_snowing_messages_pb_Msg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return snowing.messages.pb.Msgs.internal_static_snowing_messages_pb_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                snowing.messages.pb.Msgs.Msg.class, snowing.messages.pb.Msgs.Msg.Builder.class);
      }

      // Construct using snowing.messages.pb.Msgs.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        unionCase_ = 0;
        union_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return snowing.messages.pb.Msgs.internal_static_snowing_messages_pb_Msg_descriptor;
      }

      @java.lang.Override
      public snowing.messages.pb.Msgs.Msg getDefaultInstanceForType() {
        return snowing.messages.pb.Msgs.Msg.getDefaultInstance();
      }

      @java.lang.Override
      public snowing.messages.pb.Msgs.Msg build() {
        snowing.messages.pb.Msgs.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public snowing.messages.pb.Msgs.Msg buildPartial() {
        snowing.messages.pb.Msgs.Msg result = new snowing.messages.pb.Msgs.Msg(this);
        result.type_ = type_;
        if (unionCase_ == 2) {
          if (loginBuilder_ == null) {
            result.union_ = union_;
          } else {
            result.union_ = loginBuilder_.build();
          }
        }
        if (unionCase_ == 3) {
          if (loginResultBuilder_ == null) {
            result.union_ = union_;
          } else {
            result.union_ = loginResultBuilder_.build();
          }
        }
        result.unionCase_ = unionCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof snowing.messages.pb.Msgs.Msg) {
          return mergeFrom((snowing.messages.pb.Msgs.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(snowing.messages.pb.Msgs.Msg other) {
        if (other == snowing.messages.pb.Msgs.Msg.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        switch (other.getUnionCase()) {
          case LOGIN: {
            mergeLogin(other.getLogin());
            break;
          }
          case LOGINRESULT: {
            mergeLoginResult(other.getLoginResult());
            break;
          }
          case UNION_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        snowing.messages.pb.Msgs.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (snowing.messages.pb.Msgs.Msg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int unionCase_ = 0;
      private java.lang.Object union_;
      public UnionCase
          getUnionCase() {
        return UnionCase.forNumber(
            unionCase_);
      }

      public Builder clearUnion() {
        unionCase_ = 0;
        union_ = null;
        onChanged();
        return this;
      }


      private int type_ = 0;
      /**
       * <code>.snowing.messages.pb.Type type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.snowing.messages.pb.Type type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.snowing.messages.pb.Type type = 1;</code>
       * @return The type.
       */
      public snowing.messages.pb.Msgs.Type getType() {
        @SuppressWarnings("deprecation")
        snowing.messages.pb.Msgs.Type result = snowing.messages.pb.Msgs.Type.valueOf(type_);
        return result == null ? snowing.messages.pb.Msgs.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.snowing.messages.pb.Type type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(snowing.messages.pb.Msgs.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.snowing.messages.pb.Type type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          snowing.messages.pb.Msgs.Login, snowing.messages.pb.Msgs.Login.Builder, snowing.messages.pb.Msgs.LoginOrBuilder> loginBuilder_;
      /**
       * <code>.snowing.messages.pb.Login login = 2;</code>
       * @return Whether the login field is set.
       */
      public boolean hasLogin() {
        return unionCase_ == 2;
      }
      /**
       * <code>.snowing.messages.pb.Login login = 2;</code>
       * @return The login.
       */
      public snowing.messages.pb.Msgs.Login getLogin() {
        if (loginBuilder_ == null) {
          if (unionCase_ == 2) {
            return (snowing.messages.pb.Msgs.Login) union_;
          }
          return snowing.messages.pb.Msgs.Login.getDefaultInstance();
        } else {
          if (unionCase_ == 2) {
            return loginBuilder_.getMessage();
          }
          return snowing.messages.pb.Msgs.Login.getDefaultInstance();
        }
      }
      /**
       * <code>.snowing.messages.pb.Login login = 2;</code>
       */
      public Builder setLogin(snowing.messages.pb.Msgs.Login value) {
        if (loginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          union_ = value;
          onChanged();
        } else {
          loginBuilder_.setMessage(value);
        }
        unionCase_ = 2;
        return this;
      }
      /**
       * <code>.snowing.messages.pb.Login login = 2;</code>
       */
      public Builder setLogin(
          snowing.messages.pb.Msgs.Login.Builder builderForValue) {
        if (loginBuilder_ == null) {
          union_ = builderForValue.build();
          onChanged();
        } else {
          loginBuilder_.setMessage(builderForValue.build());
        }
        unionCase_ = 2;
        return this;
      }
      /**
       * <code>.snowing.messages.pb.Login login = 2;</code>
       */
      public Builder mergeLogin(snowing.messages.pb.Msgs.Login value) {
        if (loginBuilder_ == null) {
          if (unionCase_ == 2 &&
              union_ != snowing.messages.pb.Msgs.Login.getDefaultInstance()) {
            union_ = snowing.messages.pb.Msgs.Login.newBuilder((snowing.messages.pb.Msgs.Login) union_)
                .mergeFrom(value).buildPartial();
          } else {
            union_ = value;
          }
          onChanged();
        } else {
          if (unionCase_ == 2) {
            loginBuilder_.mergeFrom(value);
          }
          loginBuilder_.setMessage(value);
        }
        unionCase_ = 2;
        return this;
      }
      /**
       * <code>.snowing.messages.pb.Login login = 2;</code>
       */
      public Builder clearLogin() {
        if (loginBuilder_ == null) {
          if (unionCase_ == 2) {
            unionCase_ = 0;
            union_ = null;
            onChanged();
          }
        } else {
          if (unionCase_ == 2) {
            unionCase_ = 0;
            union_ = null;
          }
          loginBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.snowing.messages.pb.Login login = 2;</code>
       */
      public snowing.messages.pb.Msgs.Login.Builder getLoginBuilder() {
        return getLoginFieldBuilder().getBuilder();
      }
      /**
       * <code>.snowing.messages.pb.Login login = 2;</code>
       */
      public snowing.messages.pb.Msgs.LoginOrBuilder getLoginOrBuilder() {
        if ((unionCase_ == 2) && (loginBuilder_ != null)) {
          return loginBuilder_.getMessageOrBuilder();
        } else {
          if (unionCase_ == 2) {
            return (snowing.messages.pb.Msgs.Login) union_;
          }
          return snowing.messages.pb.Msgs.Login.getDefaultInstance();
        }
      }
      /**
       * <code>.snowing.messages.pb.Login login = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          snowing.messages.pb.Msgs.Login, snowing.messages.pb.Msgs.Login.Builder, snowing.messages.pb.Msgs.LoginOrBuilder> 
          getLoginFieldBuilder() {
        if (loginBuilder_ == null) {
          if (!(unionCase_ == 2)) {
            union_ = snowing.messages.pb.Msgs.Login.getDefaultInstance();
          }
          loginBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              snowing.messages.pb.Msgs.Login, snowing.messages.pb.Msgs.Login.Builder, snowing.messages.pb.Msgs.LoginOrBuilder>(
                  (snowing.messages.pb.Msgs.Login) union_,
                  getParentForChildren(),
                  isClean());
          union_ = null;
        }
        unionCase_ = 2;
        onChanged();;
        return loginBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          snowing.messages.pb.Msgs.LoginResult, snowing.messages.pb.Msgs.LoginResult.Builder, snowing.messages.pb.Msgs.LoginResultOrBuilder> loginResultBuilder_;
      /**
       * <code>.snowing.messages.pb.LoginResult loginResult = 3;</code>
       * @return Whether the loginResult field is set.
       */
      public boolean hasLoginResult() {
        return unionCase_ == 3;
      }
      /**
       * <code>.snowing.messages.pb.LoginResult loginResult = 3;</code>
       * @return The loginResult.
       */
      public snowing.messages.pb.Msgs.LoginResult getLoginResult() {
        if (loginResultBuilder_ == null) {
          if (unionCase_ == 3) {
            return (snowing.messages.pb.Msgs.LoginResult) union_;
          }
          return snowing.messages.pb.Msgs.LoginResult.getDefaultInstance();
        } else {
          if (unionCase_ == 3) {
            return loginResultBuilder_.getMessage();
          }
          return snowing.messages.pb.Msgs.LoginResult.getDefaultInstance();
        }
      }
      /**
       * <code>.snowing.messages.pb.LoginResult loginResult = 3;</code>
       */
      public Builder setLoginResult(snowing.messages.pb.Msgs.LoginResult value) {
        if (loginResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          union_ = value;
          onChanged();
        } else {
          loginResultBuilder_.setMessage(value);
        }
        unionCase_ = 3;
        return this;
      }
      /**
       * <code>.snowing.messages.pb.LoginResult loginResult = 3;</code>
       */
      public Builder setLoginResult(
          snowing.messages.pb.Msgs.LoginResult.Builder builderForValue) {
        if (loginResultBuilder_ == null) {
          union_ = builderForValue.build();
          onChanged();
        } else {
          loginResultBuilder_.setMessage(builderForValue.build());
        }
        unionCase_ = 3;
        return this;
      }
      /**
       * <code>.snowing.messages.pb.LoginResult loginResult = 3;</code>
       */
      public Builder mergeLoginResult(snowing.messages.pb.Msgs.LoginResult value) {
        if (loginResultBuilder_ == null) {
          if (unionCase_ == 3 &&
              union_ != snowing.messages.pb.Msgs.LoginResult.getDefaultInstance()) {
            union_ = snowing.messages.pb.Msgs.LoginResult.newBuilder((snowing.messages.pb.Msgs.LoginResult) union_)
                .mergeFrom(value).buildPartial();
          } else {
            union_ = value;
          }
          onChanged();
        } else {
          if (unionCase_ == 3) {
            loginResultBuilder_.mergeFrom(value);
          }
          loginResultBuilder_.setMessage(value);
        }
        unionCase_ = 3;
        return this;
      }
      /**
       * <code>.snowing.messages.pb.LoginResult loginResult = 3;</code>
       */
      public Builder clearLoginResult() {
        if (loginResultBuilder_ == null) {
          if (unionCase_ == 3) {
            unionCase_ = 0;
            union_ = null;
            onChanged();
          }
        } else {
          if (unionCase_ == 3) {
            unionCase_ = 0;
            union_ = null;
          }
          loginResultBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.snowing.messages.pb.LoginResult loginResult = 3;</code>
       */
      public snowing.messages.pb.Msgs.LoginResult.Builder getLoginResultBuilder() {
        return getLoginResultFieldBuilder().getBuilder();
      }
      /**
       * <code>.snowing.messages.pb.LoginResult loginResult = 3;</code>
       */
      public snowing.messages.pb.Msgs.LoginResultOrBuilder getLoginResultOrBuilder() {
        if ((unionCase_ == 3) && (loginResultBuilder_ != null)) {
          return loginResultBuilder_.getMessageOrBuilder();
        } else {
          if (unionCase_ == 3) {
            return (snowing.messages.pb.Msgs.LoginResult) union_;
          }
          return snowing.messages.pb.Msgs.LoginResult.getDefaultInstance();
        }
      }
      /**
       * <code>.snowing.messages.pb.LoginResult loginResult = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          snowing.messages.pb.Msgs.LoginResult, snowing.messages.pb.Msgs.LoginResult.Builder, snowing.messages.pb.Msgs.LoginResultOrBuilder> 
          getLoginResultFieldBuilder() {
        if (loginResultBuilder_ == null) {
          if (!(unionCase_ == 3)) {
            union_ = snowing.messages.pb.Msgs.LoginResult.getDefaultInstance();
          }
          loginResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              snowing.messages.pb.Msgs.LoginResult, snowing.messages.pb.Msgs.LoginResult.Builder, snowing.messages.pb.Msgs.LoginResultOrBuilder>(
                  (snowing.messages.pb.Msgs.LoginResult) union_,
                  getParentForChildren(),
                  isClean());
          union_ = null;
        }
        unionCase_ = 3;
        onChanged();;
        return loginResultBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:snowing.messages.pb.Msg)
    }

    // @@protoc_insertion_point(class_scope:snowing.messages.pb.Msg)
    private static final snowing.messages.pb.Msgs.Msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new snowing.messages.pb.Msgs.Msg();
    }

    public static snowing.messages.pb.Msgs.Msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Msg>
        PARSER = new com.google.protobuf.AbstractParser<Msg>() {
      @java.lang.Override
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Msg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public snowing.messages.pb.Msgs.Msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:snowing.messages.pb.Login)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string pid = 1;</code>
     * @return The pid.
     */
    java.lang.String getPid();
    /**
     * <code>string pid = 1;</code>
     * @return The bytes for pid.
     */
    com.google.protobuf.ByteString
        getPidBytes();

    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code snowing.messages.pb.Login}
   */
  public  static final class Login extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:snowing.messages.pb.Login)
      LoginOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Login.newBuilder() to construct.
    private Login(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Login() {
      pid_ = "";
      password_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Login();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Login(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              pid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return snowing.messages.pb.Msgs.internal_static_snowing_messages_pb_Login_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return snowing.messages.pb.Msgs.internal_static_snowing_messages_pb_Login_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              snowing.messages.pb.Msgs.Login.class, snowing.messages.pb.Msgs.Login.Builder.class);
    }

    public static final int PID_FIELD_NUMBER = 1;
    private volatile java.lang.Object pid_;
    /**
     * <code>string pid = 1;</code>
     * @return The pid.
     */
    public java.lang.String getPid() {
      java.lang.Object ref = pid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pid_ = s;
        return s;
      }
    }
    /**
     * <code>string pid = 1;</code>
     * @return The bytes for pid.
     */
    public com.google.protobuf.ByteString
        getPidBytes() {
      java.lang.Object ref = pid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pid_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pid_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof snowing.messages.pb.Msgs.Login)) {
        return super.equals(obj);
      }
      snowing.messages.pb.Msgs.Login other = (snowing.messages.pb.Msgs.Login) obj;

      if (!getPid()
          .equals(other.getPid())) return false;
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PID_FIELD_NUMBER;
      hash = (53 * hash) + getPid().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static snowing.messages.pb.Msgs.Login parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static snowing.messages.pb.Msgs.Login parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static snowing.messages.pb.Msgs.Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static snowing.messages.pb.Msgs.Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static snowing.messages.pb.Msgs.Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static snowing.messages.pb.Msgs.Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static snowing.messages.pb.Msgs.Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static snowing.messages.pb.Msgs.Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static snowing.messages.pb.Msgs.Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static snowing.messages.pb.Msgs.Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static snowing.messages.pb.Msgs.Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static snowing.messages.pb.Msgs.Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(snowing.messages.pb.Msgs.Login prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code snowing.messages.pb.Login}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:snowing.messages.pb.Login)
        snowing.messages.pb.Msgs.LoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return snowing.messages.pb.Msgs.internal_static_snowing_messages_pb_Login_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return snowing.messages.pb.Msgs.internal_static_snowing_messages_pb_Login_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                snowing.messages.pb.Msgs.Login.class, snowing.messages.pb.Msgs.Login.Builder.class);
      }

      // Construct using snowing.messages.pb.Msgs.Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pid_ = "";

        password_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return snowing.messages.pb.Msgs.internal_static_snowing_messages_pb_Login_descriptor;
      }

      @java.lang.Override
      public snowing.messages.pb.Msgs.Login getDefaultInstanceForType() {
        return snowing.messages.pb.Msgs.Login.getDefaultInstance();
      }

      @java.lang.Override
      public snowing.messages.pb.Msgs.Login build() {
        snowing.messages.pb.Msgs.Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public snowing.messages.pb.Msgs.Login buildPartial() {
        snowing.messages.pb.Msgs.Login result = new snowing.messages.pb.Msgs.Login(this);
        result.pid_ = pid_;
        result.password_ = password_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof snowing.messages.pb.Msgs.Login) {
          return mergeFrom((snowing.messages.pb.Msgs.Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(snowing.messages.pb.Msgs.Login other) {
        if (other == snowing.messages.pb.Msgs.Login.getDefaultInstance()) return this;
        if (!other.getPid().isEmpty()) {
          pid_ = other.pid_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        snowing.messages.pb.Msgs.Login parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (snowing.messages.pb.Msgs.Login) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object pid_ = "";
      /**
       * <code>string pid = 1;</code>
       * @return The pid.
       */
      public java.lang.String getPid() {
        java.lang.Object ref = pid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string pid = 1;</code>
       * @return The bytes for pid.
       */
      public com.google.protobuf.ByteString
          getPidBytes() {
        java.lang.Object ref = pid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pid = 1;</code>
       * @param value The pid to set.
       * @return This builder for chaining.
       */
      public Builder setPid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPid() {
        
        pid_ = getDefaultInstance().getPid();
        onChanged();
        return this;
      }
      /**
       * <code>string pid = 1;</code>
       * @param value The bytes for pid to set.
       * @return This builder for chaining.
       */
      public Builder setPidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 2;</code>
       * @return The password.
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       * @return The bytes for password.
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:snowing.messages.pb.Login)
    }

    // @@protoc_insertion_point(class_scope:snowing.messages.pb.Login)
    private static final snowing.messages.pb.Msgs.Login DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new snowing.messages.pb.Msgs.Login();
    }

    public static snowing.messages.pb.Msgs.Login getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Login>
        PARSER = new com.google.protobuf.AbstractParser<Login>() {
      @java.lang.Override
      public Login parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Login(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Login> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Login> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public snowing.messages.pb.Msgs.Login getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:snowing.messages.pb.LoginResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code snowing.messages.pb.LoginResult}
   */
  public  static final class LoginResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:snowing.messages.pb.LoginResult)
      LoginResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginResult.newBuilder() to construct.
    private LoginResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginResult() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              success_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return snowing.messages.pb.Msgs.internal_static_snowing_messages_pb_LoginResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return snowing.messages.pb.Msgs.internal_static_snowing_messages_pb_LoginResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              snowing.messages.pb.Msgs.LoginResult.class, snowing.messages.pb.Msgs.LoginResult.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    public boolean getSuccess() {
      return success_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof snowing.messages.pb.Msgs.LoginResult)) {
        return super.equals(obj);
      }
      snowing.messages.pb.Msgs.LoginResult other = (snowing.messages.pb.Msgs.LoginResult) obj;

      if (getSuccess()
          != other.getSuccess()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static snowing.messages.pb.Msgs.LoginResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static snowing.messages.pb.Msgs.LoginResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static snowing.messages.pb.Msgs.LoginResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static snowing.messages.pb.Msgs.LoginResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static snowing.messages.pb.Msgs.LoginResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static snowing.messages.pb.Msgs.LoginResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static snowing.messages.pb.Msgs.LoginResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static snowing.messages.pb.Msgs.LoginResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static snowing.messages.pb.Msgs.LoginResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static snowing.messages.pb.Msgs.LoginResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static snowing.messages.pb.Msgs.LoginResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static snowing.messages.pb.Msgs.LoginResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(snowing.messages.pb.Msgs.LoginResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code snowing.messages.pb.LoginResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:snowing.messages.pb.LoginResult)
        snowing.messages.pb.Msgs.LoginResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return snowing.messages.pb.Msgs.internal_static_snowing_messages_pb_LoginResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return snowing.messages.pb.Msgs.internal_static_snowing_messages_pb_LoginResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                snowing.messages.pb.Msgs.LoginResult.class, snowing.messages.pb.Msgs.LoginResult.Builder.class);
      }

      // Construct using snowing.messages.pb.Msgs.LoginResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        success_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return snowing.messages.pb.Msgs.internal_static_snowing_messages_pb_LoginResult_descriptor;
      }

      @java.lang.Override
      public snowing.messages.pb.Msgs.LoginResult getDefaultInstanceForType() {
        return snowing.messages.pb.Msgs.LoginResult.getDefaultInstance();
      }

      @java.lang.Override
      public snowing.messages.pb.Msgs.LoginResult build() {
        snowing.messages.pb.Msgs.LoginResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public snowing.messages.pb.Msgs.LoginResult buildPartial() {
        snowing.messages.pb.Msgs.LoginResult result = new snowing.messages.pb.Msgs.LoginResult(this);
        result.success_ = success_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof snowing.messages.pb.Msgs.LoginResult) {
          return mergeFrom((snowing.messages.pb.Msgs.LoginResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(snowing.messages.pb.Msgs.LoginResult other) {
        if (other == snowing.messages.pb.Msgs.LoginResult.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        snowing.messages.pb.Msgs.LoginResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (snowing.messages.pb.Msgs.LoginResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       * @return The success.
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:snowing.messages.pb.LoginResult)
    }

    // @@protoc_insertion_point(class_scope:snowing.messages.pb.LoginResult)
    private static final snowing.messages.pb.Msgs.LoginResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new snowing.messages.pb.Msgs.LoginResult();
    }

    public static snowing.messages.pb.Msgs.LoginResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginResult>
        PARSER = new com.google.protobuf.AbstractParser<LoginResult>() {
      @java.lang.Override
      public LoginResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public snowing.messages.pb.Msgs.LoginResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snowing_messages_pb_Msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snowing_messages_pb_Msg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snowing_messages_pb_Login_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snowing_messages_pb_Login_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snowing_messages_pb_LoginResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snowing_messages_pb_LoginResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\022\023snowing.messages.pb\"\235\001\n\003Msg" +
      "\022\'\n\004type\030\001 \001(\0162\031.snowing.messages.pb.Typ" +
      "e\022+\n\005login\030\002 \001(\0132\032.snowing.messages.pb.L" +
      "oginH\000\0227\n\013loginResult\030\003 \001(\0132 .snowing.me" +
      "ssages.pb.LoginResultH\000B\007\n\005union\"&\n\005Logi" +
      "n\022\013\n\003pid\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"\036\n\013Logi" +
      "nResult\022\017\n\007success\030\001 \001(\010*#\n\004Type\022\t\n\005LOGI" +
      "N\020\000\022\020\n\014LOGIN_RESULT\020\001B\006B\004Msgsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_snowing_messages_pb_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_snowing_messages_pb_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snowing_messages_pb_Msg_descriptor,
        new java.lang.String[] { "Type", "Login", "LoginResult", "Union", });
    internal_static_snowing_messages_pb_Login_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_snowing_messages_pb_Login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snowing_messages_pb_Login_descriptor,
        new java.lang.String[] { "Pid", "Password", });
    internal_static_snowing_messages_pb_LoginResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_snowing_messages_pb_LoginResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snowing_messages_pb_LoginResult_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
