// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_LOGIN  Type = 0
	Type_LOGOUT Type = 1
	Type_PLAYER Type = 2
)

var Type_name = map[int32]string{
	0: "LOGIN",
	1: "LOGOUT",
	2: "PLAYER",
}

var Type_value = map[string]int32{
	"LOGIN":  0,
	"LOGOUT": 1,
	"PLAYER": 2,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

type Msg struct {
	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=pb.Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Union:
	//	*Msg_Player
	//	*Msg_Login
	//	*Msg_Logout
	Union                isMsg_Union `protobuf_oneof:"union"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_LOGIN
}

type isMsg_Union interface {
	isMsg_Union()
}

type Msg_Player struct {
	Player *Player `protobuf:"bytes,2,opt,name=player,proto3,oneof"`
}

type Msg_Login struct {
	Login *Login `protobuf:"bytes,3,opt,name=login,proto3,oneof"`
}

type Msg_Logout struct {
	Logout *Logout `protobuf:"bytes,4,opt,name=logout,proto3,oneof"`
}

func (*Msg_Player) isMsg_Union() {}

func (*Msg_Login) isMsg_Union() {}

func (*Msg_Logout) isMsg_Union() {}

func (m *Msg) GetUnion() isMsg_Union {
	if m != nil {
		return m.Union
	}
	return nil
}

func (m *Msg) GetPlayer() *Player {
	if x, ok := m.GetUnion().(*Msg_Player); ok {
		return x.Player
	}
	return nil
}

func (m *Msg) GetLogin() *Login {
	if x, ok := m.GetUnion().(*Msg_Login); ok {
		return x.Login
	}
	return nil
}

func (m *Msg) GetLogout() *Logout {
	if x, ok := m.GetUnion().(*Msg_Logout); ok {
		return x.Logout
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Msg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Msg_Player)(nil),
		(*Msg_Login)(nil),
		(*Msg_Logout)(nil),
	}
}

type Login struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *Login) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type Logout struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Logout) Reset()         { *m = Logout{} }
func (m *Logout) String() string { return proto.CompactTextString(m) }
func (*Logout) ProtoMessage()    {}
func (*Logout) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *Logout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logout.Unmarshal(m, b)
}
func (m *Logout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logout.Marshal(b, m, deterministic)
}
func (m *Logout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logout.Merge(m, src)
}
func (m *Logout) XXX_Size() int {
	return xxx_messageInfo_Logout.Size(m)
}
func (m *Logout) XXX_DiscardUnknown() {
	xxx_messageInfo_Logout.DiscardUnknown(m)
}

var xxx_messageInfo_Logout proto.InternalMessageInfo

type Player struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *Player) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *Player) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.Type", Type_name, Type_value)
	proto.RegisterType((*Msg)(nil), "pb.Msg")
	proto.RegisterType((*Login)(nil), "pb.Login")
	proto.RegisterType((*Logout)(nil), "pb.Logout")
	proto.RegisterType((*Player)(nil), "pb.Player")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x14, 0x84, 0xb3, 0x49, 0x76, 0xed, 0x3e, 0x41, 0xc2, 0x1e, 0x24, 0x07, 0x0f, 0x35, 0x78, 0xa8,
	0x1e, 0x02, 0xd6, 0x5f, 0xa0, 0x28, 0xad, 0xb0, 0x9a, 0xb2, 0xd4, 0x83, 0xc7, 0x84, 0x86, 0x25,
	0x10, 0xb3, 0x4b, 0x93, 0x22, 0xf9, 0x2d, 0xfe, 0x59, 0x79, 0x2f, 0x01, 0xaf, 0xde, 0x26, 0x33,
	0x93, 0x8f, 0xd9, 0x07, 0xf2, 0xab, 0xb7, 0xb9, 0x3f, 0xba, 0xc1, 0xa9, 0xd0, 0x57, 0xd9, 0x0f,
	0x83, 0xe8, 0xad, 0xb7, 0xea, 0x0a, 0xe2, 0x61, 0xf4, 0x75, 0xca, 0x96, 0x6c, 0x75, 0xb1, 0x5e,
	0xe4, 0xbe, 0xca, 0xf7, 0xa3, 0xaf, 0x0d, 0xb9, 0xea, 0x06, 0x84, 0x6f, 0xcb, 0xb1, 0x3e, 0xa6,
	0xe1, 0x92, 0xad, 0xce, 0xd7, 0x80, 0xf9, 0x8e, 0x9c, 0x6d, 0x60, 0xe6, 0x4c, 0x5d, 0x03, 0x6f,
	0x9d, 0x6d, 0xba, 0x34, 0xa2, 0x92, 0xc4, 0x92, 0x46, 0x63, 0x1b, 0x98, 0x29, 0x41, 0x50, 0xeb,
	0xac, 0x3b, 0x0d, 0x69, 0xfc, 0x07, 0xd2, 0xe4, 0x20, 0x68, 0xca, 0x9e, 0xce, 0x80, 0x9f, 0xba,
	0xc6, 0x75, 0xd9, 0x3d, 0x70, 0x02, 0xa8, 0x04, 0x22, 0xdf, 0x1c, 0x68, 0x9d, 0x34, 0x28, 0xd5,
	0x25, 0x08, 0x5f, 0xf6, 0xfd, 0xf7, 0x81, 0x26, 0x49, 0x33, 0x7f, 0x65, 0x0b, 0x10, 0x13, 0x2f,
	0x7b, 0x06, 0x31, 0x4d, 0xfc, 0xff, 0xdf, 0xd8, 0x2c, 0x6d, 0x4d, 0x0f, 0xe0, 0x06, 0xe5, 0xdd,
	0x2d, 0xc4, 0x78, 0x08, 0x25, 0x81, 0xeb, 0x62, 0xf3, 0xfa, 0x9e, 0x04, 0x0a, 0x40, 0xe8, 0x62,
	0x53, 0x7c, 0xec, 0x13, 0x86, 0x7a, 0xa7, 0x1f, 0x3f, 0x5f, 0x4c, 0x12, 0x56, 0x82, 0xce, 0xfa,
	0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x93, 0x58, 0x8f, 0x99, 0x63, 0x01, 0x00, 0x00,
}
