-record(player,{name,password,level}).
-record(login,{name,password}).
-record(login_ok,{player}).
-record(login_fail,{reason}).
-record(invite,{fromName,toName}).
-record(stone,{color,x,y,is_pass}).
-record(put_stone,{gid,stone}).
